### DISCUSSION TITLE
The configuration file format may change from YAML to something else in the future

### DISCUSSION THREAD

**Discussion by masnagam** [mirakc/mirakc#1679] [Ideas]
`mirakc` uses [`serde_yaml`](https://crates.io/crates/serde-yaml) to read a configuation file in YAML format. As you can see in the linked page, this crate was deprecated. So, we have to replace it with another crate that is maintained **actively**.

If there is no such crate supporing YAML, we need to change the format to something else. No decision has been made at this point.

One of candiate formats is [TOML](https://toml.io/en/).  TOML is supported by [`serde`](https://serde.rs/#data-formats) and `cargo` uses this format.

We can look for online/offline tools to convert YAML data to TOML data. But the result may look somewhat odd to users. Because there are multiple representations for a single YAML data in TOML.  For example, the following YAML data:

```yaml
onair-program-trackers:
  gr-tracker:
    local:
      channel-types: [GR]
      uses:
        tuner: gr-tracker
```

can be represented in the following TOML representation:

```toml
# Converted by `jyt y2t`
[onair-program-trackers.gr-tracker.local]
channel-types = ["GR"]

[onair-program-trackers.gr-tracker.local.uses]
tuner = "gr-tracker"
```

The following TOML is one of other representation of the  same YAML data:

```toml
[onair-program-trackers.gr-tracker.local]
channel-types = ["GR"]
uses = { tuner = "gr-tracker" }
```

The second one looks better than the first one (at least for me).
