### ISSUE TITLE
Export timeshift records as files using FUSE

### ISSUE THREAD

**Issue by masnagam** [mirakc/mirakc#169]
Currently, there is no easy way to play timeshift records.
Implementing a frontend supporting the timeshift API is one of candidates, but it takes time.

As an alternative, we implement a feature to export timeshift records as files using [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace).
We expect that this feature makes it easy for users to play records with media players like VLC and KODI which support MPEG2-TS.

The structure of the `timeshift` config will be changed like below:

```yaml
timeshift:
  mount: /path/to/mount-point
  recorders:
    nhk:
      ...
```

[zargony/fuse-rs](https://github.com/zargony/fuse-rs) is used for the filesystem implementation.
