### ISSUE TITLE
Does this run on macOS? 

### ISSUE THREAD

**Issue by dvcrn** [mirakc/mirakc#203]
Really cool project! 

I'm wondering if this is usable on macOS (mirakurun isn't). I'm looking for a way to repurpose my mac server for DVR without having to go through a VM / Raspberry Pi . 

The article here mentions macOS as supported - https://qiita.com/masnagam/items/e71a234f2e66b1246a37 but I wasn't sure if that's still up to date. 

If it does, do you know what tuners are compatible with this when using macOS host?

**Comment by masnagam** [comment]
You can run mirakc on macOS.  In fact, I develops it on macOS and `cargo test` and `cargo run` work without any error.

However, I've never tested it on macOS with **real** tuners.  Ordinarily I use the following tuner settings for test purposes on macOS:

```yaml
tuners:
  - name: tuner1
    types: [GR,BS]
    command: >-
      curl -fsSL http://mirakc:40772/api/channels/{{{channel_type}}}/{{{channel}}}/stream
```

> do you know what tuners are compatible with this when using macOS host?

Unfortunately, I don't know.  We can find TV tuners for macOS by googling:
https://www.google.com/search?q=macos+tv+tuner

If you can find a tuner program similar to `recpt1`, you may build a DVR system using mirakc on macOS.
