### ISSUE TITLE
trouble with using multiple tuners

### ISSUE THREAD

**Issue by aftertommy** [mirakc/mirakc#2156]
## Background
First off, thank you so much for making `mirakc`. I've finally gotten around to consolidating my dvr setup to a single proxmox machine, and I've since moved over to `mirakc` to keep resource usage low and simplify things.

## My setup
- Tuners
  - PX-Q1UD
  - PX-W3PE5
- Tuner software 
  - backend: `recisdb`
  - command: `recisdb tune --device [device] --channel {{{channel}}}`

I have two Plex tuners in my setup, a PX-Q1UD and a PX-W3PE5. While the PX-W3PE5 is able to tune to `kvt`, the PX-Q1UD isn't able to. I _assume_ this just comes down to hardware capabilities and signal strength. I've confirmed this by running the tuner command passing the different devices.

## The Problem
If I attempt to tune to the channel with `mirakc`, it tries to do so using the PX-Q1UD, then fails to tune.

## Proposed Solution
It seems like `mirakc` could do a couple of things to alleviate the issue.

### `config.yml` Additions
`channels` entries could gain an optional `tuners` property, which is an array of tuner indices. If specified, only those tuners will be used for the channel. e.g.:

```yaml
channels:
  - name: tvk
    type: GR
    channel: T18
    tuners: [0, 1] # only PX-W3PE5 1 and PX-W3PE5 2 will tune this channel
tuners:
  - name: 'PX-W3PE5 1'
     ... details omitted ...
  - name: 'PX-W3PE5 2'
  - name: 'PX-Q1UD 1'
  - name: 'PX-Q1UD 2'
  - name: 'PX-Q1UD 3'
  - name: 'PX-Q1UD 4'
```

### Fallback Behavior
If `mirakc` failed to tune to a channel with a tuner, perhaps it could fall back to another one and try there? This might not be a good idea, since it could result in long times to tune channels, but I'm offering it for consideration.

I'm partial to the `config.yml` proposal. There's also a good chance that `mirakc` already provides some other way of working around this issue. If so, then that's great! I apologize if I've missed anything -- I've read through the documentation and the できるmirakc wiki, but didn't see anything about this.

I apologize for the lengthy post. If anything doesn't make sense, please ask. もし日本語で伝えやすそうなことがあれば、日本語でも大丈夫です。どうぞよろしくお願いします。

**Comment by masnagam** [comment]
thank you for your report.

as you mentioned in the post, the first direction looks better to me.
a similar configuration called `uses` has already been added for the on-air trackers and timeshift recorders.

`tuners[].name` is just a label and not unique in `tuners[]` at this point.
so, we need to use indexes for specifying tuners in `channels[].tuners[]`.
this is somewhat less readable.
if we enforce the uniquness of `tuners[].name`, we can use it instead of the index, but this is a breaking change.

mirakc might have to switch to another tuner if failed to open a tuner.
because a failure might happen even if we add `channels[].tuners[]`.
but i think this is another story and should be handled in a separate issue.

anyway, i'd like to solve this issue by the first solution (of course, PR is welcome).

**Comment by masnagam** [comment]
`StartStreaming` message includes an `EpgChannel` to open, but it's not a `ChannelConfig`.
`EpgChannel` holds only EPG-related info and implements `Deserialize` in order to save EPG data together with others.

we can copy `channels[].tuners[]` from `ChannelConfig` to `EpgChannel`, but this is a breaking change if we save the copied data to JSON files.
if we don't save, there will be `EpgChannel`s that don't have `tuners[]`...
this may cause internal inconsistency...

**Comment by masnagam** [comment]
another solution similar to this direction is like this:

```yaml
tuners:
  - name: PX-Q1UD 1
    excluded-channels:
      - channel-type: GR
        channel: T18
```

**Comment by aftertommy** [comment]
I think I like the [tuners approach](https://github.com/mirakc/mirakc/issues/2156#issuecomment-2567233517) more. That resolves the issue of readability for sure.

**Comment by masnagam** [comment]
the tuners approach may solve your issue, but i have some questions.

`TunerConfig` has the following properties other than `channel_type` and `channel` (and `disabled`):

- `extra_args` (copied to `EpgChannel::extra_args`)
- `services` (copied to `EpgChannel::services`)
- `excluded_services` (copied to `excluded_services`)

`services` and `excluded_services` probably do not affect tuner device configuration, but `extra_args` may affect.
i've never used `extra_args` and i don't know whether we have to add `extra-args` to `tuners[].excluded-channels[]`...

**Comment by masnagam** [comment]
anyway, i can add `extra-args` to `tuners[].excluded-channels[]`.

**Comment by masnagam** [comment]
started implementing...

**Comment by masnagam** [comment]
slightly improved config:

```yaml
tuners:
  - name: PX-Q1UD 1
    excluded-channels:
      # we can specify tuner names if the tuner names are unique.
      - name: tvk
      # otherwise, specify type/channel
      - channel:
          type: GR
          channel: T18
```
