### ISSUE TITLE
タイムシフト録画のファイルサイズがchunk-size*num-chunksより大きくなる

### ISSUE THREAD

**Issue by vroad** [mirakc/mirakc#712]
引き続き https://github.com/vroad/mirakc/commit/825f06fc1a263ed7829c15dc68ab6abb6614be0b を使っているのですが、
一部のm2tsファイルが既にfallocateで確保したサイズより大きいサイズになっています。

```yml
timeshift:
  recorders:
    ytv:
      service-triple: [32725, 32725, 2088]
      ts-file: /mnt/hdd0/mirakc/timeshift/ytv.timeshift.m2ts
      data-file: /var/lib/mirakc/timeshift/ytv.timeshift.json
      num-chunks: 167778
      chunk-size: 163840000
```

```
❯ echo $((163840000*167778))
27488747520000
```

この値をfallocateコマンドに渡して確保しましたが、
一部のファイルは既にこのサイズを超えました。
昨夜からタイムシフト録画に使っているHDDの空き容量が低下し始めたのですが、このせいだと思います。

古いバージョンを使い続けていたため
現在のバージョンでは修正されているか分からないです。

truncateコマンドを使えば最後の方にある部分の録画が失われる代わりにもとのファイルサイズに戻せるでしょうか。

```
❯ ls -la
total 13574453596
drwxr-xr-x 1 mirakc users           608 Jan 11 22:37 .
drwxr-xr-x 1 mirakc users            48 Jan 11 09:23 ..
-rw-r--r-- 1 mirakc users         20655 Jan 11 22:37 kbs.timeshift.json
-rw-r--r-- 1 mirakc users             0 Jan 11 09:39 kbs.timeshift.json.lock
-rw-r--r-- 1 mirakc users 2748907520000 Jan 29 10:27 kbs.timeshift.m2ts
-rw-r--r-- 1 mirakc users         29972 Jan 11 22:37 nhke.timeshift.json
-rw-r--r-- 1 mirakc users             0 Jan 11 09:40 nhke.timeshift.json.lock
-rw-r--r-- 1 mirakc users 2748907520000 Jan 29 10:27 nhke.timeshift.m2ts
-rw-r--r-- 1 mirakc users         21451 Jan 11 22:37 nhk.timeshift.json
-rw-r--r-- 1 mirakc users             0 Jan 11 09:39 nhk.timeshift.json.lock
-rw-r--r-- 1 mirakc users 2837794439168 Jan 29 10:27 nhk.timeshift.m2ts
-rw-r--r-- 1 mirakc users         21274 Jan 11 22:37 suntv.timeshift.json
-rw-r--r-- 1 mirakc users             0 Jan 11 09:40 suntv.timeshift.json.lock
-rw-r--r-- 1 mirakc users 2748907520000 Jan 29 10:27 suntv.timeshift.m2ts
-rw-r--r-- 1 mirakc users         18098 Jan 11 22:37 ytv.timeshift.json
-rw-r--r-- 1 mirakc users             0 Jan 11 09:39 ytv.timeshift.json.lock
-rw-r--r-- 1 mirakc users 2815723356160 Jan 29 10:27 ytv.timeshift.m2ts
```

**Comment by masnagam** [comment]
一部のファイルのみで発生しているみたいですね．v1運用時には一度も発生しなかったので，mainのみで発生しているのかもしれません．

> truncateコマンドを使えば最後の方にある部分の録画が失われる代わりにもとのファイルサイズに戻せるでしょうか

この問題に遭遇したことがないので分かりません．もしjsonファイルにtruncateで消えてしまうチャンクを含むレコードが登録されているなら，いろいろおかしくなりそうな気がします．truncateの後`mirakc rebuild-timeshift`でdata-fileを再構築したほうが安全だと思われます．

main最新版使うことになりますが，こちらでも発生するかどうか確認してみます．

**Comment by masnagam** [comment]
クローズされたようなので，原因がわかったか問題が解決したのだと思います．もし，こちらで確認が必要な問題が見つかったら，再オープンしてください．

**Comment by vroad** [comment]
すみませんが、lsの結果と並べると桁が違うので
単に計算間違えただけのようです。
計算結果をコピペするときに桁数が少なくて気づかなかったのかもしれません。

27488747520000
2748907520000

**Comment by masnagam** [comment]
あー，たまにやりますね．．

config.ymlの設定値を見て，fallocateを実行するスクリプトでも作っておいたほうがよいかもしれませんね．

**Comment by vroad** [comment]
なるほど、その方が安全ですね。
`mirakc rebuild-timeshift`の存在を知らなかったのですが、 #690 で追加されたコマンドですね。試してみます。
truncate前に安全のためにHDDでbtrfsスナップショット取得してからやろうと思います。

**Comment by masnagam** [comment]
それがいいです．

最近作ったばかりで，私がテストしただけなので，不具合がある可能性があります．
新しいts-fileに書き込むので，ストレージに余裕がないと実行できませんが，元データが消えることはありません（同じファイル名とかになっていなければ）．

**Comment by masnagam** [comment]
> 同じファイル名とかになっていなければ

この場合，正しく動作しないのでチェックしてエラーになるように修正しておきます．

**Comment by vroad** [comment]
とりえあず、以前別のマシンに退避したままそのままになってるm2tsに対して実行してみようと思い、
047d4b2f5fb16f27bf64793247de60d1f2449865 からビルドしたmirakcとmirakc-aribで
rebuild-timeshiftを実行しましたが、service-tripleの代わりのservice-idの指定方法が分からないです。

service-tripleの1つ目の数字と3つ目の数字を連結すればいいのか？と思いましたがそうではないようですね。

```yml
    abc:
      service-id: 327232072
      ts-file: /media/hdd/mirakc/rebuild-timeshift/abc.timeshift.m2ts
      data-file: /media/hdd/mirakc/rebuild-timeshift/abc.timeshift.json
      num-chunks: 17848
      chunk-size: 154009600
```

以下のコマンドで実行してもずっと終わらず、ファイルも何も作られません。
service-id: 3272302072
でも同様です。最初はHDDから読み込んでいる音がしばらくしますが、その後音が止んでも
コマンドの実行が終わりません。

```
 mirakc --config config.yml rebuild-timeshift abc /media/hdd/mirakc/btrbk_snapshots/timeshift.20230103T1600/abc.timeshift.m2ts --chunk-size 163840000
```
